python main_all.py --model resnet --shape 0
python main_all.py --model resnet --shape 1
python main_all.py --model resnet --shape 2
python main_all.py --model resnet --shape 3
python main_all.py --model vgg  --shape 0
python main_all.py --model vgg  --shape 1
python main_all.py --model vgg  --shape 2
python main_all.py --model vgg  --shape 3
python main_all.py --model inception  --shape 0
python main_all.py --model inception  --shape 1
python main_all.py --model inception  --shape 2
python main_all.py --model inception  --shape 3
